apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: wanderlust
  labels:
    app: backend-deployment-label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-service-label
  template:
    metadata:
      name: backend-pod
      labels:
        app: backend-service-label
    spec:
      containers:
        - name: backend-container
          image: pratiksha1999/wanderlust-backend-image:v12
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: wanderlust
spec:
  selector:
    app: backend-service-label
  type: NodePort
  ports:
  - protocol: TCP
    port:  8080
    targetPort: 8080
    nodePort: 31100
    
  