apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-PV
  namespace: wanderlust
spec:
  capacity:
    storage: 5Gi
  volumeModes: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/db