@Library('Shared') _
pipeline {
    
    agent any
    
    parameters{
        string(name: 'FRONTEND_DOCKER_TAG', defaultValue: '', description: 'This docker tag will recieve input from CI pipeline for Frontend docker tag')
        string(name: 'BACKEND_DOCKER_TAG', defaultValue: '', description: 'This docker tag will recieve input from CI pipeline for backend docker tag')
    }

    stages {
        stage('Workspace Cleanup') {
            steps {
                script {
                    cleanWs()
                }
            }
        }

        stage('Git: Code Checkout') {
            steps {
                script {
                    git_checkout('https://github.com/pratiksha-design261/Project_Wanderlust.git','master')
                }
            }
        }

        stage('Verify: Docker Image Tag') {
            steps {
                script {
                    echo "FRONTEND DOCKER TAG: ${FRONTEND_DOCKER_TAG}"
                    echo "BACKEND DOCKER TAG: ${BACKEND_DOCKER_TAG}"
                }
            }
        }
        

        stage('Update: Kubernetes Manifests') {
            steps {
                script {
                    dir('kubernetes') {
                        // sh "echo ${pwd}"
                        // sh "sudo chmod -R u+w ${pwd}"
                        // sh "echo ${ls -l}"
                        sh """
                            sed -i -e s/wanderlust-backend-image.*/wanderlust-backend-image:${params.BACKEND_DOCKER_TAG}/g backend.yaml
                        """
                    }
                    dir('kubernetes') {
                        sh """
                            sed -i -e s/wanderlust-frontend-image.*/wanderlust-frontend-image:${params.FRONTEND_DOCKER_TAG}/g frontend.yaml
                        """
                    }
                }
            }
        }

        stage('Git: Upadte and push the code to Github') {
            steps {
                script {
                        echo "checking github repository:"
                        sh "git status"

                        echo "adding modified file to git:"
                        sh "git add ."

                        echo "commiting changes:"
                        sh 'git commit -m "Updated env variales"'

                        echo "Pushing changes to github:"
                        withCredentials([usernamePassword(credentialsId: 'github', usernameVariable: 'GIT_USERNAME', passwordVariable: 'GIT_PASSWORD')]) {
                            sh "git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/pratiksha-design261/Project_Wanderlust.git master"
                        }
                }
            }
        }
    }

    post {
        success {
            script {
                emailext attachLog: true,
                from: 'pratiksha123dhotre@gmail.com',
                subject: "Wanderlust project has been updaed and deployed - '${currentBuild.result}'",
                body: """
                    <html>
                    <body>
                        <div style="background-color: #FFA07A; padding: 10px; margin-bottom: 10px;">
                            <p style="color: black; font-weight: bold;">Project: ${env.JOB_NAME}</p>
                        </div>
                        <div style="background-color: #90EE90; padding: 10px; margin-bottom: 10px;">
                            <p style="color: black; font-weight: bold;">Build Number: ${env.BUILD_NUMBER}</p>
                        </div>
                        <div style="background-color: #87CEEB; padding: 10px; margin-bottom: 10px;">
                            <p style="color: black; font-weight: bold;">URL: ${env.BUILD_URL}</p>
                        </div>
                    </body>
                    </html>
            """,
            to: 'dhotrepratiksha123@gmail.com',
            mimeType: 'text/html'
            }
        }

        failure {
            script {
                emailext attachLog: true,
                from: 'pratiksha123dhotre@gmail.com',
                subject: "Wanderlust project has been updaed and deployed - '${currentBuild.result}'",
                body: """
                    <html>
                    <body>
                        <div style="background-color: #FFA07A; padding: 10px; margin-bottom: 10px;">
                            <p style="color: black; font-weight: bold;">Project: ${env.JOB_NAME}</p>
                        </div>
                        <div style="background-color: #90EE90; padding: 10px; margin-bottom: 10px;">
                            <p style="color: black; font-weight: bold;">Build Number: ${env.BUILD_NUMBER}</p>
                        </div>
                    </body>
                    </html>
                """,
            to: 'dhotrepratiksha123@gmail.com',
            mimeType: 'text/html'
            }
        }
    }
}
